"""Add new tables (e.g., TableName)

Revision ID: 75848f689861
Revises: 2d4476eccc07
Create Date: 2025-05-01 22:08:42.785172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75848f689861'
down_revision = '2d4476eccc07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
